---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
version: 1
name: atomic-niri-itterum
description: Bazzite DX GNOME with Niri.

base-image: ghcr.io/ublue-os/bazzite-dx-nvidia-gnome
image-version: stable

modules:
  - type: dnf
    repos:
      copr:
        - avengemedia/danklinux
        - avengemedia/dms
    install:
      packages:
        - niri
        - dms
        - helix

  - type: files
    files:
      - source: system
        destination: /

  - type: signing
