---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: template
description: This is my personal OS image.

base-image: ghcr.io/wayblueorg/niri
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - atim/starship
        - avengemedia/dms

    install:
      packages:
        - helix
        - starship
        - quickshell
        - dms
        - foot
        - greetd

    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: brew
    brew-analytics: false

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - com.brave.Browser
          - org.gnome.Loupe
      - scope: user

  - type: signing
